version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      major:
        update-types: [major]
      minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: "weekly"
